#!/usr/bin/env bash
# this will change where localhose and facebook resolve to.
cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost/' ~/hosts.new
echo '8.8.8.8 facebook.com' >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts